#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file=requirements.nix requirements.in
#
attrs==19.3.0             # via jsonschema
backcall==0.1.0           # via ipython
bleach==3.1.0             # via nbconvert
cycler==0.10.0            # via matplotlib
decorator==4.4.1          # via ipython, traitlets
defusedxml==0.6.0         # via nbconvert
entrypoints==0.3          # via nbconvert
ipykernel==5.1.3          # via ipywidgets, jupyter, jupyter-console, notebook, qtconsole
ipython-genutils==0.2.0   # via nbformat, notebook, qtconsole, traitlets
ipython==7.11.1
ipywidgets==7.5.1         # via jupyter
jedi==0.15.2              # via ipython
jinja2==2.10.3            # via nbconvert, notebook
jsonschema==3.2.0         # via nbformat
jupyter-client==5.3.4     # via ipykernel, jupyter-console, notebook, qtconsole
jupyter-console==6.1.0    # via jupyter
jupyter-core==4.6.1       # via jupyter-client, nbconvert, nbformat, notebook, qtconsole
jupyter==1.0.0
kiwisolver==1.1.0         # via matplotlib
markupsafe==1.1.1         # via jinja2
matplotlib==3.1.2
mistune==0.8.4            # via nbconvert
mpmath==1.1.0             # via sympy
nbconvert==5.6.1          # via jupyter, notebook
nbformat==5.0.4           # via ipywidgets, nbconvert, notebook
nose==1.3.7
notebook==6.0.3           # via jupyter, widgetsnbextension
numpy==1.18.1
pandas==0.25.3
pandocfilters==1.4.2      # via nbconvert
parso==0.5.2              # via jedi
patsy==0.5.1              # via statsmodels
pexpect==4.8.0            # via ipython
pickleshare==0.7.5        # via ipython
prometheus-client==0.7.1  # via notebook
prompt-toolkit==3.0.2     # via ipython, jupyter-console
ptyprocess==0.6.0         # via pexpect, terminado
pygments==2.5.2           # via ipython, jupyter-console, nbconvert, qtconsole
pyparsing==2.4.6          # via matplotlib
pyrsistent==0.15.7        # via jsonschema
python-dateutil==2.8.1    # via jupyter-client, matplotlib, pandas
pytz==2019.3              # via pandas
pyzmq==18.1.1             # via jupyter-client, notebook
qtconsole==4.6.0          # via jupyter
scipy==1.4.1
send2trash==1.5.0         # via notebook
six==1.14.0               # via bleach, cycler, jsonschema, patsy, pyrsistent, python-dateutil, traitlets
statsmodels==0.11.0
sympy==1.5.1
terminado==0.8.3          # via notebook
testpath==0.4.4           # via nbconvert
tornado==6.0.3            # via ipykernel, jupyter-client, notebook, terminado
traitlets==4.3.3          # via ipykernel, ipython, ipywidgets, jupyter-client, jupyter-core, nbconvert, nbformat, notebook, qtconsole
wcwidth==0.1.8            # via prompt-toolkit
webencodings==0.5.1       # via bleach
widgetsnbextension==3.5.1  # via ipywidgets

# The following packages are considered to be unsafe in a requirements file:
# setuptools
